using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using WrenSharp.SourceGenerator.Models;

namespace WrenSharp.SourceGenerator.Attributes;

public static partial class Templates
{
    public static SourceText BindingClass(ImmutableArray<WrenClassModel> classes)
    {
        var sb = new IndentedStringBuilder();
        sb.AppendLine("""
                      // <auto-generated/>
                      using WrenSharp;

                      namespace WrenSharp.Interop;

                      public class WrenBinding : IWrenModuleProvider {
                      """);

        using (sb.Indented())
        {

            GenerateBindMethod(sb, classes);
            sb.AppendLine();
            
            GenerateModuleDictionary(sb, classes);
            sb.AppendLine();
            
            GenerateGetModuleSource(sb, classes);
            sb.AppendLine();
            
            GenerateOnModuleLoadComplete(sb);
        }

        sb.AppendLine("}");

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private static void GenerateModuleDictionary(IndentedStringBuilder sb, ImmutableArray<WrenClassModel> classes)
    {
        var modules = classes.GroupBy(c => c.Module);
        
        sb.AppendLine("private static string GetModuleSource(string moduleName) => moduleName switch");
        sb.AppendLine("{");
        using (sb.Indented())
        {
            foreach (var module in modules)
            {
                sb.Append('"').Append(module.Key).Append('"').Append(" => string.Concat(");
                sb.Append(string.Join(", ", module.Select(obj => $"{obj.Namespace}.{obj.CsName}.Source + '\\n'")));
                sb.AppendLine("),");
            }
            
            sb.AppendLine("_ => null");
        }
            
        sb.AppendLine("};");
    }

    private static void GenerateBindMethod(IndentedStringBuilder sb, ImmutableArray<WrenClassModel> classes)
    {
        sb.AppendLine("public static void Bind(WrenSharpVM vm)");
        sb.AppendLine("{");
        using (sb.Indented())
        {
            foreach (var model in classes)
            {
                sb.AppendLine($"{model.Namespace}.{model.CsName}.BindTo(vm);");
            }
        }

        sb.AppendLine("}");
    }

    private static void GenerateGetModuleSource(IndentedStringBuilder sb, ImmutableArray<WrenClassModel> classes)
    {
        sb.AppendLine("public IWrenSource GetModuleSource(WrenVM vm, string moduleName) {");
        using (sb.Indented())
        {
            
            sb.AppendLine("var source = GetModuleSource(moduleName);");
            sb.AppendLine("if (source != null)");
            sb.Indent().AppendLine("return new WrenStringSource(source);");
            
            sb.AppendLine("return null;");
        }

        sb.AppendLine("}");
    }

    private static void GenerateOnModuleLoadComplete(IndentedStringBuilder sb)
    {
        sb.AppendLine("public void OnModuleLoadComplete(WrenVM vm, string module, IWrenSource source)");
        sb.AppendLine("{");
        sb.AppendLine("}");
    }
}