using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis.Text;
using WrenSharp.SourceGenerator.Models;

namespace WrenSharp.SourceGenerator.Attributes;

public static partial class Templates
{
    public static SourceText BindingClass(ImmutableArray<WrenClassModel> classes)
    {
        var sb = new StringBuilder();
        
        foreach(var model in classes)
        {
            sb.AppendLine($"{model.CsName}Extensions.BindTo(vm);");
        }
        return SourceText.From($$"""
// <auto-generated/>
using WrenSharp;

namespace WrenSharp.Interop;

public static class Binding {
   public static void Bind(WrenSharpVM vm) {
       {{sb}}
   }
}
""", Encoding.UTF8);
    }
}