using System.CodeDom.Compiler;
using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using WrenSharp.SourceGenerator.Models;

namespace WrenSharp.SourceGenerator;

public partial class WrenInterop
{
    private static void EmitClass(SourceProductionContext spc, WrenClassModel target)
    {
        foreach (var diagnostic in target.Diagnostics)
        {
            spc.ReportDiagnostic(diagnostic);
        }
        
        if (target.Diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
            return;

        var source = GeneratedSource(target);
        
        spc.AddSource($"{target.CsName}.WrenInterop.g.cs", source);
    }

    private static string ConvertNameToWrenStyle(string csharpName)
    {
        if (string.IsNullOrEmpty(csharpName))
            return csharpName;
        
        return char.ToLowerInvariant(csharpName[0]) + csharpName.Substring(1);
    }

    private static SourceText GeneratedSource(WrenClassModel target)
    {
        var sb = new IndentedStringBuilder();
        
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by WrenSharp.SourceGenerator from [WrenClass] on " + target.CsName + ".");
        sb.AppendLine("#nullable disable");

        if (target.Namespace is not null)
            sb.AppendLine($"using {target.Namespace};");


        sb.AppendLine("namespace WrenSharp.Interop;");
        sb.Append($"static class {target.CsName}Extensions");
        sb.AppendLine(" {");

        sb.Indent();


        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Registers the \"{target.Name}\"foreign class in module \"{target.Module}\",");
        sb.AppendLine("/// generated from [WrenMethod]/[WrenProperty] members of this type.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static void BindTo(WrenSharpVM vm)");
        sb.AppendLine("{");

        sb.Indent();
        
        var wrenClassName = target.Name ?? ConvertNameToWrenStyle(target.CsName);

        sb.AppendLine($"""vm.Foreign("{target.Module}", "{wrenClassName}")""");

        AddConstructors(sb, target);
        
        AddMethods(sb, target);
        
        sb.AppendLine(";");
        

        sb.Unindent();
        sb.AppendLine("}");
        sb.Unindent();
        sb.AppendLine("}");
        
        
        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private static void AddConstructors(IndentedStringBuilder sb, WrenClassModel model)
    {
        if (model.Constructors.Length == 0) return;
        
        sb.AppendLine($".Allocate((WrenCallContext ctx, ref WrenSharedDataHandle data) =>");
        sb.AppendLine("{");

        sb.Indent();

        sb.AppendLine("List<WrenType> args = [];");
        sb.AppendLine("for(var i = 0; i < ctx.VM.GetSlotCount() - 1; i++)");
        
        using(sb.Indented())
            sb.AppendLine("args.Add(ctx.GetArgType(i));");

        sb.AppendLine();

        sb.AppendLine("Console.WriteLine(args);");
        sb.Append(model.CsName).AppendLine(" instance = args switch {");
        sb.Indent();

        foreach (var ctor in model.Constructors)
        {
            AddConstructor(sb, ctor);
            sb.AppendLine(", ");
        }

        sb.AppendLine("_ => throw new NotImplementedException()");
        sb.Unindent();
        sb.AppendLine("};");
        sb.AppendLine();
        sb.AppendLine("data = ctx.VM.SharedData.Add(instance);");
        
        sb.Unindent();

        sb.AppendLine("})");
    }

    private static void AddConstructor(IndentedStringBuilder sb, WrenConstructor constructor)
    {
        sb.Append('[');

        sb.Append(string.Join(", ", 
            constructor.Parameters.Select(param =>
                $"WrenType.{WrenTypeExtensions.FromCsharpType(param.Type).ToString()}"))
        );

        sb.Append(']');

        sb.Append(" => new(");
        var slot = 0;
        
        
        foreach (var parameter in constructor.Parameters)
        {
            sb.Append(WrenTypeExtensions.ToWrenGetArgMethod(parameter.Type, slot++));
            
            if (slot < constructor.Parameters.Count)
            {
                sb.Append(", ");
            }
        }

        sb.Append(")");
    }
    
    public static void AddMethods(IndentedStringBuilder sb, WrenClassModel model)
    {
        if (model.Methods.Length == 0) return;

        foreach (var method in model.Methods)
        {
            if (method.IsStatic)
            {
                AddStaticMethod(sb, method, model.CsName);
            }
            else
            {
                AddInstanceMethod(sb, method, model.CsName);
            }
        }
    }
    
    private static void AddStaticMethod(IndentedStringBuilder sb, WrenMethod method, string csClassName)
    {
        sb.AppendLine($""".Static("{method.GetSignature()}", ctx =>""");
        sb.AppendLine("{");

        using (sb.Indented())
        {
            if (method.ReturnType != "void")
                sb.Append("ctx.Return(");

            sb.AppendLine($"{csClassName}.{method.CsMethodName}(");

            using (sb.Indented())
            {
                var slot = 0;
                foreach (var parameter in method.Parameters)
                {
                    sb.Append(WrenTypeExtensions.ToWrenGetArgMethod(parameter.Type, slot++));
                    if (slot < method.Parameters.Count)
                        sb.AppendLine(",");
                    else sb.AppendLine();
                }
            }

            if (method.ReturnType != "void")
                sb.AppendLine(")");

            sb.AppendLine(");");
        }
        
        sb.AppendLine("})");
    }

    private static void AddInstanceMethod(IndentedStringBuilder sb, WrenMethod method, string csClassName)
    {
        sb.AppendLine($""".Instance("{method.GetSignature()}", ctx =>""");
        sb.AppendLine("{");

        using (sb.Indented())
        {
            sb.AppendLine($"var self = ctx.GetReceiverSharedData<{csClassName}>();");

            if (method.ReturnType != "void")
                sb.Append("ctx.Return(");

            sb.AppendLine($"self.{method.CsMethodName}(");

            using (sb.Indented())
            {
                var slot = 0;
                foreach (var parameter in method.Parameters)
                {
                    sb.Append(WrenTypeExtensions.ToWrenGetArgMethod(parameter.Type, slot++));
                    if (slot < method.Parameters.Count)
                        sb.AppendLine(",");
                    else sb.AppendLine();
                }
            }

            if (method.ReturnType != "void")
                sb.AppendLine(")");

            sb.AppendLine(");");
        }
        
        sb.AppendLine("})");
    }
}