using System.Collections.Immutable;
using System.Diagnostics;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using WrenSharp.SourceGenerator.helpers;
using WrenSharp.SourceGenerator.Models;

namespace WrenSharp.SourceGenerator;

public partial class WrenInterop
{
    private static void EmitClass(SourceProductionContext spc, WrenClassModel target)
    {
        foreach (var diagnostic in target.Diagnostics)
        {
            spc.ReportDiagnostic(diagnostic);
        }

        if (target.Diagnostics.Any(d => d.Severity == DiagnosticSeverity.Error))
            return;

        var source = GeneratedSource(target);

        spc.AddSource($"{target.CsName}.WrenInterop.g.cs", source);
    }

    private static SourceText GeneratedSource(WrenClassModel target)
    {
        var sb = new IndentedStringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by WrenSharp.SourceGenerator from [WrenClass] on " + target.CsName + ".");
        sb.AppendLine("#nullable disable");
        sb.AppendLine($"using WrenSharp;");

        sb.AppendLine();

        sb.AppendLine($"namespace {target.Namespace};");
        sb.AppendLine();

        sb.Append($"partial class {target.CsName}");
        sb.AppendLine(" {");

        sb.Indent();

        sb.Append("public static string Source => ").AppendLine("""" """ """".Trim());
        WrenCodeGenerator.Generate(sb, target);
        sb.Append("""" """ """".Trim()).AppendLine(";");

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Registers the \"{target.Name}\"foreign class in module \"{target.Module}\",");
        sb.AppendLine("/// generated from [WrenMethod]/[WrenProperty] members of this type.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static void BindTo(WrenSharpVM vm)");
        sb.AppendLine("{");

        sb.Indent();

        var wrenClassName = target.Name ?? WrenHelpers.ConvertNameToWrenStyle(target.CsName);

        sb.AppendLine($"""vm.Foreign("{target.Module}", "{wrenClassName}")""");

        AddConstructors(sb, target);

        AddMethods(sb, target);

        AddProperties(sb, target);

        sb.AppendLine(";");

        sb.Unindent();
        sb.AppendLine("}");
        sb.Unindent();
        sb.AppendLine("}");

        return SourceText.From(sb.ToString(), Encoding.UTF8);
    }

    private static void GenerateArgumentArray(IndentedStringBuilder sb)
    {
        sb.AppendLine("var argCount = ctx.VM.GetSlotCount() - 1;");
        sb.AppendLine("Span<WrenType> args = stackalloc WrenType[argCount];");
        sb.AppendLine("for(var i = 0; i < argCount; i++)");
        sb.Indent();
        sb.AppendLine("args[i] = ctx.GetArgType(i);");
        sb.Unindent();
        sb.AppendLine();
    }

    private static void AddConstructors(IndentedStringBuilder sb, WrenClassModel model)
    {
        if (model.Constructors.Length == 0) return;

        sb.AppendLine($".Allocate(static (WrenCallContext ctx, ref WrenSharedDataHandle data) =>");
        sb.AppendLine("{");
        using (sb.Indented())
        {
            GenerateArgumentArray(sb);

            sb.Append(model.CsName).AppendLine(" instance = args switch {");
            sb.Indent();

            foreach (var ctor in model.Constructors)
            {
                AddConstructor(sb, ctor);
                sb.AppendLine(", ");
            }

            sb.AppendLine("_ => throw new NotImplementedException()");
            sb.Unindent();
            sb.AppendLine("};");
            sb.AppendLine();
            sb.AppendLine("data = ctx.VM.SharedData.Add(instance);");
        }

        sb.AppendLine("})");
    }

    private static void AddConstructor(IndentedStringBuilder sb, WrenConstructor constructor)
    {
        sb.Append('[');

        sb.Append(string.Join(", ",
            constructor.Parameters.Select(param =>
                $"WrenType.{WrenTypeExtensions.FromCsharpType(param.Type).ToString()}"))
        );

        sb.Append(']');

        sb.Append(" => new(");
        var slot = 0;


        foreach (var parameter in constructor.Parameters)
        {
            sb.Append(WrenTypeExtensions.ToWrenGetArgMethod(parameter.Type, slot++));

            if (slot < constructor.Parameters.Count)
            {
                sb.Append(", ");
            }
        }

        sb.Append(")");
    }

    private static void AddMethods(IndentedStringBuilder sb, WrenClassModel model)
    {
        if (model.Methods.Length == 0) return;

        foreach (var methodGroup in model.Methods.GroupBy(m => m.Name))
        {
            var name = WrenHelpers.ConvertNameToWrenStyle(methodGroup.Key);

            foreach (var signatureGroup in methodGroup.GroupBy(m => (m.IsStatic, m.Parameters.Count)))
            {
                var (isStatic, paramCount) = signatureGroup.Key;
                if(isStatic) 
                    AddStaticMethod(sb, name, model.CsName, paramCount, methodGroup);
                else 
                    AddInstanceMethod(sb, name, model.CsName, paramCount, methodGroup);
            }
        }
    }
    
    private static void AddStaticMethod(IndentedStringBuilder sb, string name, string className, int parameterCount,
        IEnumerable<WrenMethod> methods)
    {
        var parameters = string.Join(", ", Enumerable.Repeat("_", parameterCount));
        sb.AppendLine($""".Static("{name}({parameters})", static ctx =>""")
            .AppendLine("{")
            .Indent();

        GenerateArgumentArray(sb);

        sb.AppendLine("switch (args)");
        sb.AppendLine("{");
        using (sb.Indented())
        {
            foreach (var method in methods)
            {
                sb.AppendLine($"case [{string.Join(", ", method.Parameters.Select(p =>
                    $"WrenType.{WrenTypeExtensions.FromCsharpType(p.Type)}"))}]:");

                using (sb.Indented())
                    GenerateMethodCall(sb, className, method);

                sb.AppendLine("break;");
            }
        }

        sb.AppendLine("}")
            .AppendLine("})");
    }
    private static void AddInstanceMethod(IndentedStringBuilder sb, string name, string className, int parameterCount,
        IEnumerable<WrenMethod> methods)
    {
        var parameters = string.Join(", ", Enumerable.Repeat("_", parameterCount));
        
        sb.AppendLine($""".Instance("{name}({parameters})", static ctx =>""")
            .AppendLine("{")
            .Indent()
            .AppendLine($"var self = ctx.GetReceiverSharedData<{className}>();");

        GenerateArgumentArray(sb);

        sb.AppendLine("switch (args)");
        sb.AppendLine("{");
        using (sb.Indented())
        {
            foreach (var method in methods)
            {
                sb.AppendLine($"case [{string.Join(", ", method.Parameters.Select(p =>
                    $"WrenType.{WrenTypeExtensions.FromCsharpType(p.Type)}"))}]:");

                using (sb.Indented())
                    GenerateMethodCall(sb, "self", method);

                sb.AppendLine("break;");
            }
        }

        sb.AppendLine("}")
            .AppendLine("})");
    }

    private static void GenerateMethodCall(IndentedStringBuilder sb, string target, WrenMethod method)
    {
        var hasReturn = method.ReturnType != "void";

        if (hasReturn)
        {
            sb.AppendLine("ctx.Return(")
                .Indent();
        }

        sb.Append(target).Append('.').Append(method.CsMethodName).Append('(');

        if (method.Parameters.Count > 0)
        {
            using (sb.Indented())
            {
                sb.AppendLine();
                var parameters = method.Parameters.Select((parameter, index) =>
                    WrenTypeExtensions.ToWrenGetArgMethod(parameter.Type, index)
                );
                sb.AppendLine(string.Join(", ", parameters));
            }
        }

        sb.Append(')');
        sb.AppendLine(hasReturn ? ");" : ";");
    }


    private static void AddProperties(IndentedStringBuilder sb, WrenClassModel model)
    {
        if (model.Properties.Length == 0) return;

        foreach (var property in model.Properties)
        {
            if (property.Getter)
                AddGetter(sb, property, model.CsName);
            if (property.Setter)
                AddSetter(sb, property, model.CsName);
        }
    }

    private static void AddGetter(IndentedStringBuilder sb, WrenProperty property, string csClassName)
    {
        sb.AppendLine($""".Instance("{WrenHelpers.ConvertNameToWrenStyle(property.Name)}", ctx => """);
        sb.AppendLine("{");
        using (sb.Indented())
        {
            sb.AppendLine($"var self = ctx.GetReceiverSharedData<{csClassName}>();");
            sb.AppendLine($"ctx.Return(self.{property.Name});");
        }

        sb.AppendLine("})");
    }

    private static void AddSetter(IndentedStringBuilder sb, WrenProperty property, string csClassName)
    {
        sb.AppendLine($""".Instance("{WrenHelpers.ConvertNameToWrenStyle(property.Name)}=(_)", ctx => """);
        sb.AppendLine("{");
        using (sb.Indented())
        {
            sb.AppendLine($"var self = ctx.GetReceiverSharedData<{csClassName}>();");
            sb.Append(property.Type);
            sb.Append(" value = ");
            sb.Append(WrenTypeExtensions.ToWrenGetArgMethod(property.Type, 0));
            sb.AppendLine(";");

            sb.AppendLine($"self.{property.Name} = value;");
        }

        sb.AppendLine("})");
    }
}